const URL = import.meta.env.VITE_REACT_APP_BE_URL
export default URL

export const JoditConfig = {
    askBeforePasteFromWord: false,
    processPasteFromWord: false,
    askBeforePasteHTML: false,
    askBeforePasteFromExcel: false,
    defaultActionOnPaste: 'insert_as_html',
    brMode: false,
    enter: 'P',
    removeFormatOnPaste: false,
    readonly: false,
    enableDragAndDropFileToEditor: true,
    buttons: [
        'source',
        '|',
        'bold',
        'italic',
        'underline',
        '|',
        'ul',
        'ol',
        '|',
        'font',
        'fontsize',
        'brush',
        'paragraph',
        '|',
        'image',
        'table',
        'link',
        '|',
        'left',
        'center',
        'right',
        'justify',
        '|',
        'undo',
        'redo',
        '|',
        'hr',
        'eraser',
        'fullsize',
    ],
    uploader: { insertImageAsBase64URI: true },
    removeButtons: ['brush', 'file'],
    showXPathInStatusbar: false,
    showCharsCounter: false,
    showWordsCounter: false,
    toolbarAdaptive: true,
    toolbarSticky: true,
}